# Generated by Django 5.2.8 on 2025-11-20 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_insumo', models.CharField(choices=[('FILTRO', 'Filtro'), ('QUIMICO', 'Químico'), ('ENVASE', 'Envase'), ('OTRO', 'Otro')], max_length=20)),
                ('unidad', models.CharField(help_text='Ej. unidad, kg, litro.', max_length=20)),
                ('stock_min', models.DecimalField(decimal_places=2, default=0, help_text='Stock mínimo recomendado.', max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('BODEGA', 'Bodega'), ('PLANTA', 'Planta'), ('PROCESO', 'Proceso'), ('ESTANQUE', 'Estanque'), ('DESPACHO', 'Despacho')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comentario', models.CharField(blank=True, max_length=255)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.insumo')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.ubicacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='productos.producto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_producto', to='inventario.ubicacion')),
            ],
            options={
                'unique_together': {('producto', 'ubicacion')},
            },
        ),
        migrations.CreateModel(
            name='StockInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventario.insumo')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_insumo', to='inventario.ubicacion')),
            ],
            options={
                'unique_together': {('ubicacion', 'insumo')},
            },
        ),
    ]
