# Generated by Django 5.2.8 on 2025-11-20 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('CRUDO', 'Agua cruda'), ('PURIFICADA', 'Agua purificada')], max_length=20)),
                ('capacidad_litros', models.PositiveIntegerField()),
                ('nivel_agua', models.DecimalField(decimal_places=2, default=0, help_text='Nivel actual de agua en litros (aprox.).', max_digits=10)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estanques', to='inventario.ubicacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nivel_min_operacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nivel_max_operacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='planta.estanque')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100)),
                ('modo_automatico', models.BooleanField(default=True)),
                ('estado_on', models.BooleanField(default=False)),
                ('estanque_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bombas_destino', to='planta.estanque')),
                ('estanque_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bombas_origen', to='planta.estanque')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
