# Generated by Django 5.2.8 on 2025-11-20 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estanque',
            name='estado',
            field=models.CharField(blank=True, help_text='Estado operativo del estanque (OK, ALERTA, MANTENCION, etc.).', max_length=50),
        ),
        migrations.CreateModel(
            name='EventoPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_hora', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('PARO', 'Paro'), ('ARRANQUE', 'Arranque'), ('MANTENCION', 'Mantención'), ('ALERTA', 'Alerta'), ('OTRO', 'Otro')], max_length=50)),
                ('descripcion', models.TextField()),
                ('severidad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='BAJA', max_length=10)),
                ('estanque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='planta.estanque')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
