# Generated by Django 5.2.7 on 2025-12-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0002_alter_estanque_estado_eventoplanta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionplanta',
            name='estanque',
        ),
        migrations.RemoveField(
            model_name='eventoplanta',
            name='estanque',
        ),
        migrations.AddField(
            model_name='estanque',
            name='ph_actual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='pH actual (solo aplica a agua purificada).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='estanque',
            name='ph_raw',
            field=models.IntegerField(blank=True, help_text='Lectura cruda del sensor pH (ADC).', null=True),
        ),
        migrations.DeleteModel(
            name='Bomba',
        ),
        migrations.DeleteModel(
            name='ConfiguracionPlanta',
        ),
        migrations.DeleteModel(
            name='EventoPlanta',
        ),
    ]
