# Generated by Django 5.2.7 on 2025-12-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0003_remove_configuracionplanta_estanque_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estanque',
            name='ubicacion',
        ),
        migrations.AlterField(
            model_name='estanque',
            name='estado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='estanque',
            name='nivel_agua',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='estanque',
            name='ph_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='estanque',
            name='ph_raw',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
