# Generated by Django 5.2.7 on 2025-12-13 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('planta', '0004_remove_estanque_ubicacion_alter_estanque_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioBidones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('stock', models.IntegerField(default=0)),
                ('ultimo_contador_ir', models.PositiveIntegerField(default=0)),
                ('accion_pendiente', models.CharField(choices=[('NONE', 'Ninguna'), ('ADD', 'Sumar'), ('SUB', 'Restar')], default='NONE', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='estanque',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estanques', to='inventario.ubicacion'),
        ),
        migrations.AlterField(
            model_name='estanque',
            name='estado',
            field=models.CharField(blank=True, help_text='Estado operativo del estanque (OK, ALERTA, MANTENCION, etc.).', max_length=50),
        ),
        migrations.AlterField(
            model_name='estanque',
            name='nivel_agua',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Nivel actual de agua en litros (aprox.).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='estanque',
            name='ph_actual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='pH actual (solo aplica a agua purificada).', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='estanque',
            name='ph_raw',
            field=models.IntegerField(blank=True, help_text='Lectura cruda del sensor pH (ADC).', null=True),
        ),
    ]
