# Generated by Django 5.2.7 on 2025-12-16 00:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0005_inventariobidones_estanque_ubicacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventariobidones',
            old_name='ultimo_contador_ir',
            new_name='ultimo_bidones_total',
        ),
        migrations.RemoveField(
            model_name='inventariobidones',
            name='accion_pendiente',
        ),
        migrations.RemoveField(
            model_name='inventariobidones',
            name='stock',
        ),
        migrations.AddField(
            model_name='inventariobidones',
            name='modo_pendiente',
            field=models.CharField(choices=[('NONE', 'Sin acción'), ('IN', 'Entrada (+)'), ('OUT', 'Salida (-)')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='inventariobidones',
            name='stock_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventariobidones',
            name='ultima_accion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inventariobidones',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='estanque',
            name='estado',
            field=models.CharField(blank=True, help_text='Estado operativo (OK, AVISO_85, ALERTA_95, ALERTA, etc.).', max_length=50),
        ),
        migrations.AlterField(
            model_name='estanque',
            name='ph_actual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='pH calculado (ej: 7.12).', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='estanque',
            name='ph_raw',
            field=models.PositiveIntegerField(blank=True, help_text='Lectura ADC cruda del sensor pH (0-4095 aprox).', null=True),
        ),
    ]
