# Generated by Django 5.2.7 on 2025-12-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0006_rename_ultimo_contador_ir_inventariobidones_ultimo_bidones_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventariobidones',
            old_name='ultimo_bidones_total',
            new_name='ultimo_contador_esp',
        ),
        migrations.RemoveField(
            model_name='inventariobidones',
            name='ultima_actualizacion',
        ),
        migrations.AlterField(
            model_name='estanque',
            name='estado',
            field=models.CharField(blank=True, help_text='Estado operativo del estanque (OK, ALERTA, AVISO_85, ALERTA_95, etc.).', max_length=50),
        ),
        migrations.AlterField(
            model_name='estanque',
            name='ph_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='estanque',
            name='ph_raw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventariobidones',
            name='stock_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventariobidones',
            name='ultima_accion',
            field=models.CharField(blank=True, default='Sin acción', max_length=120),
        ),
    ]
