# Generated by Django 5.2.7 on 2025-12-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0007_rename_ultimo_bidones_total_inventariobidones_ultimo_contador_esp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estanque',
            name='ubicacion',
        ),
        migrations.AlterField(
            model_name='estanque',
            name='estado',
            field=models.CharField(blank=True, help_text='Estado operativo (OK, ALERTA, AVISO_85, ALERTA_95, etc.).', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventariobidones',
            name='modo_pendiente',
            field=models.CharField(blank=True, choices=[('IN', 'Ingreso'), ('OUT', 'Salida')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventariobidones',
            name='stock_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventariobidones',
            name='ultima_accion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
