# Generated by Django 5.2.7 on 2025-12-16 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('planta', '0008_remove_estanque_ubicacion_alter_estanque_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estanque',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estanques', to='inventario.ubicacion'),
        ),
        migrations.AlterField(
            model_name='estanque',
            name='estado',
            field=models.CharField(blank=True, help_text='Estado operativo del estanque (OK, ALERTA, AVISO_85, ALERTA_95, etc.).', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventariobidones',
            name='modo_pendiente',
            field=models.CharField(choices=[('NONE', 'Sin acción'), ('IN', 'Entrada (+)'), ('OUT', 'Salida (-)')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventariobidones',
            name='stock_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventariobidones',
            name='ultima_accion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
