# Generated by Django 5.2.7 on 2025-12-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0009_estanque_ubicacion_alter_estanque_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='estanque',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='estanque',
            name='ubicacion',
        ),
        migrations.AlterField(
            model_name='estanque',
            name='capacidad_litros',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='estanque',
            name='estado',
            field=models.CharField(blank=True, default='OK', max_length=30),
        ),
        migrations.AlterField(
            model_name='estanque',
            name='nivel_agua',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='estanque',
            name='nombre',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='estanque',
            name='ph_actual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estanque',
            name='tipo',
            field=models.CharField(choices=[('CRUDO', 'Agua cruda'), ('PURIFICADA', 'Agua purificada')], default='CRUDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventariobidones',
            name='modo_pendiente',
            field=models.CharField(choices=[('NONE', 'Sin acción'), ('IN', 'Ingreso (+)'), ('OUT', 'Salida (-)')], default='NONE', max_length=10),
        ),
    ]
