# Generated by Django 5.2.7 on 2025-12-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0010_eventoplanta_remove_estanque_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariobidones',
            name='stock_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventariobidones',
            name='ultimo_contador_esp',
            field=models.IntegerField(default=0),
        ),
    ]
