# Generated by Django 5.2.7 on 2025-12-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0011_alter_inventariobidones_stock_actual_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventariobidones',
            old_name='stock_actual',
            new_name='stock_10',
        ),
        migrations.AddField(
            model_name='inventariobidones',
            name='stock_20',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventariobidones',
            name='tipo_pendiente',
            field=models.CharField(choices=[('NONE', 'Sin tipo'), ('L10', 'Bidón 10L'), ('L20', 'Bidón 20L')], default='NONE', max_length=10),
        ),
    ]
