# Generated by Django 5.2.7 on 2025-12-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0012_rename_stock_actual_inventariobidones_stock_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariobidones',
            name='tipo_pendiente',
            field=models.CharField(choices=[('L10', 'Bidón 10L'), ('L20', 'Bidón 20L')], default='L10', max_length=10),
        ),
    ]
