# Generated by Django 5.2.8 on 2025-12-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comentarios_cliente',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='forma_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia bancaria')], default='EFECTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='origen',
            field=models.CharField(choices=[('INTERNO', 'Interno'), ('WEB', 'Web público')], default='INTERNO', max_length=20),
        ),
    ]
