# Generated by Django 5.2.7 on 2025-10-31 02:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('rut', models.CharField(blank=True, max_length=12)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('RECIBIDO', '1) Recibido'), ('PREPARACION', '2) En preparación'), ('EN_RUTA', '3) En ruta'), ('ENTREGADO', 'Entregado'), ('FALLIDO', 'Fallido/Devuelto')], default='RECIBIDO', max_length=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacion', models.TextField(blank=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.cliente')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.planta')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=120)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('RECIBIDO', '1) Recibido'), ('PREPARACION', '2) En preparación'), ('EN_RUTA', '3) En ruta'), ('ENTREGADO', 'Entregado'), ('FALLIDO', 'Fallido/Devuelto')], max_length=15)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('nota', models.TextField(blank=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='pedidos.pedido')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['planta', 'fecha'], name='pedidos_ped_planta__720b41_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='pedidos_ped_estado_20cbc4_idx'),
        ),
    ]
