# Generated by Django 5.2.8 on 2025-11-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='rut_dv',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='DV'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rut_numero',
            field=models.CharField(blank=True, help_text='Solo números, sin puntos ni guion.', max_length=8, null=True, verbose_name='RUT (sin DV)'),
        ),
    ]
