# Generated by Django 5.2.8 on 2025-11-20 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('volumen_litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('estanque_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_origen', to='planta.estanque')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
