# Generated by Django 5.2.7 on 2025-12-18 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0013_alter_inventariobidones_tipo_pendiente'),
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loteproduccion',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='loteproduccion',
            name='estanque_origen',
        ),
        migrations.RemoveField(
            model_name='loteproduccion',
            name='volumen_litros',
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='estanque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_produccion', to='planta.estanque'),
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='litros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
