# Generated by Django 5.2.7 on 2025-12-18 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0013_alter_inventariobidones_tipo_pendiente'),
        ('produccion', '0002_remove_loteproduccion_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteproduccion',
            name='estanque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.estanque'),
        ),
    ]
