# Generated by Django 5.2.7 on 2025-12-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_alter_loteproduccion_estanque'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteproduccion',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
