# Generated by Django 5.2.7 on 2025-12-18 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0013_alter_inventariobidones_tipo_pendiente'),
        ('produccion', '0004_loteproduccion_hora_fin_loteproduccion_hora_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteproduccion',
            name='estanque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planta.estanque'),
        ),
    ]
