# Generated by Django 5.2.8 on 2025-11-20 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('marca_modelo', models.CharField(max_length=100)),
                ('capacidad_carga_kg', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RutaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('ASIGNADA', 'Asignada'), ('CARGADA', 'Cargada'), ('EN_CAMINO', 'En camino'), ('ENTREGADA', 'Entregada')], default='ASIGNADA', max_length=20)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_conducidas', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='logistica.vehiculo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RutaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_hora_estado', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='ventas.pedido')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_pedidos', to='logistica.rutaentrega')),
            ],
            options={
                'unique_together': {('ruta', 'pedido')},
            },
        ),
    ]
