# Generated by Django 5.2.8 on 2025-12-03 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproducto',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría de producto', 'verbose_name_plural': 'Categorías de productos'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre', 'presentacion_litros'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
