# Generated by Django 5.2.8 on 2025-12-03 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_categoriaproducto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción breve del producto (uso, características, etc.).'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoría comercial del producto (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.categoriaproducto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_lista',
            field=models.DecimalField(decimal_places=2, help_text='Precio de lista en pesos chilenos.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='presentacion_litros',
            field=models.DecimalField(decimal_places=2, help_text='Capacidad del envase en litros (ej. 10, 20, 19.50).', max_digits=5),
        ),
    ]
