# Generated by Django 5.2.8 on 2025-12-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_descripcion_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen del producto (opcional).', null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción breve del producto.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_lista',
            field=models.DecimalField(decimal_places=2, help_text='Precio de venta en pesos chilenos.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='presentacion_litros',
            field=models.DecimalField(decimal_places=2, help_text='Capacidad del envase en litros (ej. 10, 20, 19.5).', max_digits=5),
        ),
    ]
