# Generated by Django 5.2.7 on 2025-10-31 02:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('llegada', models.DateTimeField(blank=True, null=True)),
                ('salida', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='pendiente', max_length=15)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RutaDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('chofer', models.CharField(max_length=100)),
                ('vehiculo', models.CharField(max_length=60)),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('en_ruta', 'En ruta'), ('cerrada', 'Cerrada')], default='planificada', max_length=15)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.planta')),
            ],
        ),
    ]
