# Generated by Django 5.2.7 on 2025-10-31 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribucion', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutaparada',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='rutaparada',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='distribucion.rutadistribucion'),
        ),
        migrations.AlterUniqueTogether(
            name='rutaparada',
            unique_together={('ruta', 'pedido')},
        ),
    ]
