# Generated by Django 5.2.7 on 2025-10-31 01:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistPH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('valor_ph', models.DecimalField(decimal_places=3, max_digits=6)),
                ('evidencia_url', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('volumen_real_l', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tds', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('uvi', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('orp', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('bloqueado', 'Bloqueado')], default='abierto', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=5, max_digits=14)),
                ('unidad', models.CharField(max_length=15)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('calidad_ok', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regla', models.CharField(max_length=100)),
                ('condicion', models.CharField(max_length=20)),
                ('umbral', models.DecimalField(decimal_places=5, max_digits=14)),
                ('severidad', models.CharField(choices=[('info', 'Info'), ('warn', 'Advertencia'), ('high', 'Alta')], default='warn', max_length=10)),
                ('activa', models.BooleanField(default=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.planta')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('reconocida', 'Reconocida'), ('cerrada', 'Cerrada')], default='abierta', max_length=15)),
                ('alarma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad.alarma')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.planta')),
            ],
        ),
    ]
