# Generated by Django 5.2.7 on 2025-10-31 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calidad', '0001_initial'),
        ('iot', '0001_initial'),
        ('usuarios', '0002_alter_usuario_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmalog',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iot.sensor'),
        ),
        migrations.AddField(
            model_name='checklistph',
            name='firmado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistph',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.planta'),
        ),
        migrations.AddField(
            model_name='lote',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iot.estacionllenado'),
        ),
        migrations.AddField(
            model_name='lote',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lote',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.planta'),
        ),
        migrations.AddField(
            model_name='medicion',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calidad.lote'),
        ),
        migrations.AddField(
            model_name='medicion',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.planta'),
        ),
        migrations.AddField(
            model_name='medicion',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iot.sensor'),
        ),
        migrations.AddIndex(
            model_name='alarma',
            index=models.Index(fields=['planta', 'activa'], name='calidad_ala_planta__54334c_idx'),
        ),
        migrations.AddIndex(
            model_name='alarma',
            index=models.Index(fields=['severidad'], name='calidad_ala_severid_e5b0ff_idx'),
        ),
        migrations.AddIndex(
            model_name='alarmalog',
            index=models.Index(fields=['planta', 'timestamp'], name='calidad_ala_planta__356369_idx'),
        ),
        migrations.AddIndex(
            model_name='alarmalog',
            index=models.Index(fields=['estado'], name='calidad_ala_estado_3d43ae_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistph',
            index=models.Index(fields=['planta', 'fecha'], name='calidad_che_planta__d9d283_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistph',
            unique_together={('planta', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['planta', 'fecha'], name='calidad_lot_planta__54e230_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['estado'], name='calidad_lot_estado_21f86d_idx'),
        ),
        migrations.AddIndex(
            model_name='medicion',
            index=models.Index(fields=['planta', 'timestamp'], name='calidad_med_planta__28ee75_idx'),
        ),
        migrations.AddIndex(
            model_name='medicion',
            index=models.Index(fields=['sensor', 'timestamp'], name='calidad_med_sensor__2bee25_idx'),
        ),
    ]
