# Generated by Django 5.2.8 on 2025-11-20 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SectorEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=50)),
                ('recargo_delivery', models.DecimalField(decimal_places=2, default=0, help_text='Recargo adicional por delivery asociado a este sector.', max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('rut_numero', models.CharField(max_length=8, verbose_name='RUT (sin DV)')),
                ('rut_dv', models.CharField(max_length=1, verbose_name='DV')),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('sector_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='clientes.sectorentrega')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
