# Generated by Django 5.2.7 on 2025-12-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='rut_dv',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='rut_numero',
        ),
        migrations.AddField(
            model_name='cliente',
            name='dv',
            field=models.CharField(blank=True, help_text='Dígito verificador (0-9 o K).', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rut',
            field=models.CharField(blank=True, help_text='RUT sin puntos ni guion (7 u 8 dígitos).', max_length=8, null=True),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('rut', 'dv'), name='uq_rut_dv_cliente'),
        ),
    ]
