# Generated by Django 5.2.7 on 2025-12-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_rut_dv_remove_cliente_rut_numero_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cliente',
            name='uq_rut_dv_cliente',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dv',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='DV'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='RUT (sin DV)'),
        ),
        migrations.AlterField(
            model_name='sectorentrega',
            name='recargo_delivery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('rut__isnull', False)), fields=('rut', 'dv'), name='uq_rut_dv_cliente'),
        ),
    ]
