# Generated by Django 5.2.8 on 2025-11-20 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('planta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('codigo', models.CharField(choices=[('NIVEL', 'Nivel'), ('CONTADOR', 'Contador'), ('PH', 'pH'), ('OTRO', 'Otro')], max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('codigo', models.CharField(help_text='Identificador lógico del sensor (ej. NIVEL_CRUDO_01).', max_length=50, unique=True)),
                ('unidad', models.CharField(max_length=20)),
                ('rango_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rango_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estanque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensores', to='planta.estanque')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensores', to='inventario.ubicacion')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensores', to='sensores.tiposensor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LecturaSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_hora', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=3, max_digits=12)),
                ('calidad', models.CharField(blank=True, max_length=20)),
                ('severidad', models.CharField(blank=True, max_length=20)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='sensores.sensor')),
            ],
            options={
                'ordering': ('-fecha_hora',),
            },
        ),
    ]
