# Generated by Django 5.2.8 on 2025-11-20 07:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actuador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('BOMBA', 'Bomba de agua'), ('VALVULA', 'Válvula'), ('RELE', 'Relé')], max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('estado_on', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='estado',
            field=models.CharField(choices=[('OK', 'OK'), ('FUERA_RANGO', 'Fuera de rango'), ('SIN_DATOS', 'Sin datos')], default='SIN_DATOS', max_length=20),
        ),
        migrations.AlterField(
            model_name='lecturasensor',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tiposensor',
            name='codigo',
            field=models.CharField(choices=[('NIVEL', 'Sensor de nivel'), ('CONTADOR', 'Sensor contador IR'), ('PH', 'Sensor de pH'), ('OTRO', 'Otro tipo de sensor')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tiposensor',
            name='descripcion',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('mensaje', models.CharField(max_length=250)),
                ('severidad', models.CharField(choices=[('INFO', 'Informativa'), ('WARNING', 'Advertencia'), ('CRITICA', 'Crítica')], max_length=20)),
                ('atendida', models.BooleanField(default=False)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='sensores.sensor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReglaControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100)),
                ('condicion', models.CharField(choices=[('MAYOR', 'Valor mayor a'), ('MENOR', 'Valor menor a'), ('IGUAL', 'Valor igual a')], max_length=20)),
                ('umbral', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mensaje', models.CharField(default='Condición de regla cumplida', max_length=200)),
                ('actuador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglas', to='sensores.actuador')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='sensores.sensor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
