# Generated by Django 5.2.8 on 2025-11-20 19:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0002_actuador_sensor_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturaCrudaESP32',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('sensor_id', models.CharField(max_length=100)),
                ('nivel_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ir_estado', models.IntegerField(blank=True, null=True)),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
