# Generated by Django 5.2.8 on 2025-11-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('rut_numero', models.CharField(max_length=8, verbose_name='RUT (sin DV)')),
                ('rut_dv', models.CharField(max_length=1, verbose_name='DV')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('contacto', models.CharField(blank=True, help_text='Nombre de la persona de contacto principal.', max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
