# Generated by Django 5.2.7 on 2025-12-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_remove_proveedor_rut_dv_remove_proveedor_rut_numero_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='proveedor',
            name='uq_rut_dv_proveedor',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='dv',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='DV'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rut',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='RUT (sin DV)'),
        ),
    ]
