# Generated by Django 5.2.7 on 2025-12-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_remove_proveedor_uq_rut_dv_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='rut',
            field=models.CharField(blank=True, help_text='Sin puntos ni guion, solo los 7 u 8 dígitos.', max_length=8, null=True, verbose_name='RUT (sin DV)'),
        ),
    ]
