# Generated by Django 5.2.7 on 2025-10-31 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('serie', models.CharField(blank=True, max_length=50)),
                ('ubicacion', models.CharField(blank=True, max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.planta')),
            ],
        ),
        migrations.CreateModel(
            name='EstacionLlenado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('caudal_nominal_lpm', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.planta')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ph', 'pH'), ('tds', 'TDS'), ('uvi', 'UV Intensity'), ('orp', 'ORP'), ('nivel', 'Nivel'), ('caudal', 'Caudal'), ('presion', 'Presión')], max_length=30)),
                ('unidad', models.CharField(max_length=15)),
                ('topico_mqtt', models.CharField(max_length=160, unique=True)),
                ('rango_min', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('rango_max', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('calibracion', models.JSONField(blank=True, default=dict)),
                ('activo', models.BooleanField(default=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iot.equipo')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.planta')),
            ],
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['planta', 'tipo'], name='iot_equipo_planta__1a5bd3_idx'),
        ),
        migrations.AddIndex(
            model_name='estacionllenado',
            index=models.Index(fields=['planta'], name='iot_estacio_planta__3250c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='estacionllenado',
            unique_together={('planta', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['planta', 'tipo'], name='iot_sensor_planta__d4e72e_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['activo'], name='iot_sensor_activo_6019ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together={('planta', 'tipo', 'topico_mqtt')},
        ),
    ]
